[package]
name = "programming_pearls"
version = "0.1.0"
authors = ["Rodrigo Valle <rodrigo.d.valle@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]